Jasonette/JASONETTE-Android

app/src/main/assets/rss
app/src/main/assets/timers
app/src/main/java/com/jasonette/seed/Action/JasonConvertAction.java

@gliechtenstein Here is my take on the convert.rss feature for Android. I refactored some things for more code reuse in that file while I was there. I tried the Jasonpedia example and a youtube feed, and both worked great. Seems pretty zippy with J2V8

add $convert.rss feature

---

app/src/main/java/com/jasonette/seed/Component/JasonComponentFactory.java
app/src/main/java/com/jasonette/seed/Component/JasonHtmlComponent.java
app/src/main/java/com/jasonette/seed/Section/ItemAdapter.java

This implements the HTML component, issue #30. One small caveat, to make wrapped components work properly, I had to add 1px padding.

#30 html component

---

README.md

Added links to docs and download, updated links to quickstart. Similar to https://github.com/Jasonette/JASONETTE-iOS/pull/100

Changes to links on README

---

app/src/main/java/com/jasonette/seed/Action/JasonUtilAction.java

Now $util.alert can support input fields

Issue 40,input fields in alert

---

app/src/main/java/com/jasonette/seed/Component/JasonComponentFactory.java
app/src/main/java/com/jasonette/seed/Component/JasonSliderComponent.java

Implement SliderComponent https://github.com/Jasonette/JASONETTE-Android/issues/29

Add JasonSliderComponent

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/jasonette/seed/Component/JasonComponentFactory.java
app/src/main/java/com/jasonette/seed/Component/JasonMapComponent.java
app/src/main/java/com/jasonette/seed/Core/JasonViewActivity.java
app/src/main/res/values/strings.xml

@gliechtenstein Here's what I've put together for the map component. I don't remember if you wanted to merge this now and separate to an extension later, or just wait to do it in an extension first.
I had to add an `OnItemTouchListener` to the `RecyclerView` in order to intercept touch events but I tried to do it in a way that keeps most of the code in the component fle, and extensions should be able to take advantage of it too.
One thing I was not able to get working is rounded corners. The current technique for rounded corners does not work. I have some proof of concept code to get it working a different way, but you have to specify the background color for the rounded corner shape (can't just be transparent) and it wouldn't work with a camera background... Let me know if you want to …

Map component

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/assets/parser
app/src/main/java/com/jasonette/seed/Action/JasonOauthAction.java
app/src/main/java/com/jasonette/seed/Core/JasonModel.java
app/src/main/java/com/jasonette/seed/Core/JasonViewActivity.java

This is Jasonette OAuth action for Android.
It currently supports:
- OAuth 1
- Standard protocol
- Basic authentication
- OAuth 2
- Code grant
- Direct access token grant
- Password grant (**needs testing**)
- Refresh tokens
Some samples working:
Tumblr (OAuth 1):
Reddit (OAuth 2 - scopes, state and refresh tokens):
Facebook (OAuth 2, direct access token in auth phase and normal flow)

$oauth action

---

app/src/main/java/com/jasonette/seed/Core/JasonViewActivity.java

Related: https://github.com/Jasonette/JASONETTE-iOS/pull/232
I have noticed a frequent usage pattern where the current `$show` and `$load` syntax cannot support easily.
This happens in the following case:
1. The user load a static JASON markup WITHOUT doing a `$render` on load.
2. The user also wants to make sure that the page is always fresh when the view comes back from another view.
3. Normally people try to achieve this by setting a `$show` handler and doing a `"type": "$reload"`, like this:
```
{
"$jason": {
"head": {
"actions": {
"$show": {
"type": "$reload"
}
}
},
"body": {
"sections": [{
"items": [{
...
}]
}]
}
}
}
```
Notice how the `body` is immediately under `$jason`, which means everything is server-side rendered and there is no `$render` action.
What happens in this case is: …

Updated policy for $show and $load

---

.gitignore

This file is generated by android studio and is user personal.

Add .idea/codeStyleSettings.xml in .gitignore

---

app/src/main/java/com/jasonette/seed/Core/JasonViewActivity.java

This patch avoids multiple ImageView creation (like for webview)

Check that backgroundImageView is not created

---

app/build.gradle
app/src/debug/AndroidManifest.xml
app/src/debug/java/com/jasonette/seed/Launcher/DebugLauncher.java
app/src/main/java/com/jasonette/seed/Core/JasonModel.java
app/src/main/java/com/jasonette/seed/Helper/JasonHelper.java
app/src/main/java/com/jasonette/seed/Launcher/Launcher.java

Stetho allows debugging Android apps using the Chrome Developer tools.
Given that Jasonette is heavily based on network and json usage, Chrome Dev tools is helpful for debugging.

Add Stetho to allow debugging of network & ui

---

app/src/main/java/com/jasonette/seed/Core/JasonViewActivity.java

This patch fix webview background and refactor ImageView background

Fix webview background

---

app/src/main/java/com/jasonette/seed/Core/JasonViewActivity.java
app/src/main/java/com/jasonette/seed/Lib/BackgroundCameraManager.java

You all waited it... Here the pull request !! :wink: 
You can already try it, but I will do refactoring to improve the code.
@gliechtenstein look forward that you test it!

Add Camera support in background (see #78)

---

app/src/main/java/com/jasonette/seed/Action/JasonAudioAction.java

Return data:uri for recorded audio file

---

app/src/main/java/com/jasonette/seed/Core/JasonViewActivity.java

Put search icon on right hand side of the toolbar

---

app/src/main/java/com/jasonette/seed/Core/JasonViewActivity.java

Remove code duplication when setting border

---

app/src/main/java/com/jasonette/seed/Launcher/Launcher.java

As discussed in https://github.com/Jasonette/Jasonette/issues/7

$env.app.version & $env.app.build

---

app/build.gradle
app/src/debug/AndroidManifest.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/jasonette/seed/Action/JasonPushAction.java
app/src/main/java/com/jasonette/seed/Core/JasonViewActivity.java
app/src/main/java/com/jasonette/seed/Launcher/Launcher.java
app/src/main/java/com/jasonette/seed/Service/push/JasonPushMessageService.java
app/src/main/java/com/jasonette/seed/Service/push/JasonPushRegisterService.java
build.gradle

Added Firebase Push Messaging.
To activate, go to `tools > firebase > cloud messaging` and connect with firebase. (First need to have a google developer account)
Architecture-wise, there are two parts: `action` and `service`.
- Action stays stateless and ephemeral as before.
- Service is stateful and persistent.
An action can instantiate multiple services. In this case we need to instantiate two separate services--one for registration (`JasonPushMessageService`) and the other for messages (`JasonPushRegisterService`)

Jason push action

---

app/src/main/java/com/jasonette/seed/Action/JasonNetworkAction.java

Previously it defaulted to PUT method and data was encoded.
... I'm quite new to the whole forking&PR process, so please let me know if I should do something differently 👍

Fix network request action POST method with JSON data to work correctly

---

app/src/main/java/com/jasonette/seed/Service/agent/JasonAgentService.java

Background web containers ship with progress bars built in.
This only applies to background web containers and not components.
Additional attributes added through this PR:
- style
- background: the default background color of the web container
- progress: progress bar color
```
{
...
"body": {
"style": {
"background": {
"type": "html",
"style": {
"background": "#ffffff",
"progress": "#ff0000"
}
}
}
}
}
```

progressbar on web containers

---

app/src/main/assets/st

Declare local variables inside templates. See https://github.com/SelectTransform/st.js/blob/develop/test/unit/transform/let.js for details

#let api for template parser

---

app/src/main/java/com/jasonette/seed/Core/JasonViewActivity.java
app/src/main/java/com/jasonette/seed/Launcher/Launcher.java

- $href with success bug fix
- background position for when header doesn't exist

Quick Fixes
